server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        #连接池的补充设置
        #初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize : 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙,wall开启会导致flyway初始化失败错误：sql注入，操作不被允许执行
        filters: stat
        connectionProperties : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    # 使用Redis统一管理Session可以实现单点登录
    redis:
      host: 127.0.0.1
      port: 6379
      password : demo
      timeout: 0
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # 全局异常处理：抛出后会被GlobalExceptionHandler.class处理
    mvc:
      #出现错误时, 直接抛出异常
      throw-exception-if-no-handler-found: true
#    resources:
#      add-mappings: false


  # flyway 数据库版本管理工具
    flyway:
      # 启用或禁用 flyway true:启用
      enabled: true
      # 设定 SQL 脚本的目录,多个路径使用逗号分隔, 比如取值为 classpath:db/migration,filesystem:/sql-migrations
      # locations: db/migration
      # 开发环境最好开启 outOfOrder, 生产环境关闭 outOfOrder .
      out-of-order: true
      # 迁移基准线 默认为版本号为1 故初始版本号设置为V1.0.1即可
      baseline-on-migrate: true



## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.licf.demo.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

project:
  version: 1.0.0
  author: 李灿峰
  createDate: 2019-03-13

# 日志配置
logback:
  logdir: D:/idea/log
  .appname: demo


regCenter:
  serverList: localhost:2181
  namespace: elastic-job-lite-springboot

stockJob:
  # stockJob.cron为定时任务的cron表达式；
  cron: 0/5 * * * * ?
  # stockJob.shardingTotalCount为任务的分数量（即同时同时开几个定时任务）；
  shardingTotalCount: 2
  # stockJob.shardingItemParameters为任务分片携带的参数；
  shardingItemParameters: 0=Chengdu0,1=Chengdu1

